Repository ssm0318/WhoamI-Today-frontend, pull requests merged in 2025-03, with the labels that each got.

#809 (#808) 로딩시 배경화면 색 하얀색으로 변경
  src/styles/global-styles.ts
Labels: feature

#810 (#788) 친구 초대 문구 줄바꿈 수정
  src/components/friends/explore-friends/friend-invitation/FriendInvitation.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/ko/translation.json
Labels: bug

#811 (#795) 내 게시글 좋아요, 이모지 리액션 UI 수정
  src/components/_common/post-reaction-item/PostReactionItem.tsx
  src/components/_common/post-reaction-list/PostReactionList.tsx
  src/routes/Reactions.tsx
Labels: feature

#812 (#780) Ping 글자수 제한 늘리기
  src/components/ping/ping-message-input/PingMessageInput.styled.ts
  src/components/ping/ping-message-input/PingMessageInput.tsx
  src/components/ping/ping-message-item/PingMessageItem.tsx
Labels: bug

#813 (#790, #793) 친구 관계 수정 기능 관련, 친구 관계 수정 버튼 모양 변경
  src/components/profile/Profile.tsx
  src/components/profile/edit-connections/EditConnectionsBottomSheet.tsx
  src/design-system/Inputs/CheckBox.styled.ts
  src/design-system/Inputs/CheckBox.tsx
  src/design-system/Inputs/RadioButton.styled.ts
  src/design-system/Inputs/RadioButton.tsx
  src/design-system/Inputs/index.ts
  src/i18n/locales/en/translation.json
Labels: bug

#825 (#816) 체크인 노래 수정 오류
  src/components/check-in/check-in-edit/music-search-bottom-sheet/music-item/MusicItem.tsx
Labels: bug, urgent

#827 (#814) mark as read API가 잘 불리고 있는지 확인
  src/components/note/note-section/NoteSection.tsx
  src/components/response/response-section/ResponseSection.tsx
  src/utils/apis/user.ts
Labels: bug

#829 (#784) 친구 목록에서 new 플로팅 버튼이 맨 마지막 친구 가림
  src/components/header/bottom-sheet/NewPostBottomSheet.tsx
  src/components/header/floating-button/FloatingButton.styled.ts
  src/i18n/locales/en/translation.json
  src/i18n/locales/ko/translation.json
  src/routes/AllQuestions.tsx
  src/routes/My.tsx
  src/routes/friends/Friends.tsx
Labels: bug

#848 [New Feature] 게시물(Note/Response) 작성시 공개범위 설정 / 수정시 공개범위 설정 / 게시글 공개범위 표기
  src/components/note/connection-type/ConnectionTypeOption.tsx
  src/components/note/new-note-content/NewNoteContent.tsx
  src/components/note/note-item/NoteItem.tsx
  src/components/profile/edit-connections/EditConnectionsBottomSheet.tsx
  src/components/response/response-item/ResponseItem.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/ko/translation.json
  src/models/api/question.ts
  src/models/post.ts
  src/routes/notes/NewNote.tsx
  src/routes/responses/NewResponse.tsx
  src/utils/apis/note.ts
  src/utils/apis/question.ts
Labels: feature

#903 (#826) Ping 보내기 아이콘 변경
  public/icons/ping_send.svg
  src/components/friends/updated-friend-item/UpdatedFriendItem.tsx
  src/components/friends/updated-friend-item/UpdatedFriendItemDefault.tsx
  src/components/header/user-header/UserHeader.tsx
  src/design-system/SvgIcon/icons.ts
Labels: refact, ping

#905 (#777) 데스크탑에서 Ping 페이지에서 알림설정 배너가 인풋창을 가리는 버그 수정
  src/routes/Root.tsx
  src/routes/friends/FriendsFeed.tsx
  src/routes/friends/FriendsList.tsx
Labels: bug, ping

#908 (#779) ping 메시지 보낼때 리프레시 실행
  src/routes/ping/Ping.tsx
Labels: feature, ping

#910 (#909) 한글로 Ping 메시지 보낼때 마지막 글자가 한번 더 보내지는 버그 수정
  src/components/ping/ping-message-input/PingMessageInput.tsx
Labels: bug, ping

#907 (#778) Ping 페이지 입력창 스타일 수정
  public/icons/ping_emoji_add.svg
  src/components/ping/ping-message-input/PingMessageInput.tsx
  src/constants/layout.ts
Labels: MarkUp, refact, ping

#911 (#787) 유저페이지 > 더보기 메뉴에서 친구그룹관리 메뉴 제거
  src/components/user-page/UserMoreModal.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/ko/translation.json
Labels: bug

#977 [New Feature] 답변 작성 버튼 #845
  src/components/_common/prompt/PromptCard.styled.ts
  src/components/_common/prompt/PromptCard.tsx
  src/components/response/question-item/QuestionItem.tsx
Labels: feature

#980 (#865) (#975) (ver. Q) 이모지 피커가 가려지지 않도록 열리는 방향을 다르게 수정
  src/components/_common/post-footer/PostFooter.tsx
  src/components/check-in/check-in-edit/check-in-emoji/CheckInEmoji.tsx
  src/components/emoji-picker/EmojiPicker.helper.ts
  src/components/emoji-picker/EmojiPicker.tsx
  src/constants/layout.ts
  src/stores/emojiPicker.ts
Labels: feature

#981 (#936) ping 메시지 줄바꿈 설정 변경
  src/components/ping/ping-message-item/PingMessageItem.tsx
Labels: refact, ping

#982 (#960) 게시글 작성 페이지 - 경고문구 위치 이동
  src/components/note/new-note-content/NewNoteContent.tsx
  src/routes/responses/NewResponse.tsx
Labels: feature, MarkUp, Post

#984 bugfix: #983 unread_noti_cnt=0인 케이스에서 화면에 0이 노출되지 않도록 처리
  src/components/header/common-header/CommonHeader.tsx
Labels: bug, MarkUp

#985 (#857) (#869) 메인탭 변경시 안읽은 노티 개수 갱신
  src/components/header/common-header/CommonHeader.tsx
Labels: bug, Notification

#987 (#906) 유저페이지에서 친구인 경우에만 Ping 페이지 이동 버튼 노출하도록 수정
  src/components/header/user-header/UserHeader.tsx
Labels: MarkUp, user, ping

#1075 (#1063) (ver. Q) 답변 목록에서 이모지 피커가 잘려서 노출되는 버그 수정
  src/components/_common/post-footer/PostFooter.tsx
  src/components/check-in/check-in-edit/check-in-emoji/CheckInEmoji.tsx
  src/components/emoji-picker/EmojiPicker.helper.ts
  src/components/emoji-picker/EmojiPicker.tsx
  src/components/response/response-section/ResponseSection.tsx
  src/stores/emojiPicker.ts
Labels: bug

#1077 (#1076) 유저페이지 스크롤 상태 유지가 되지 않는 버그 수정
  src/routes/UserPage.tsx
Labels: bug

#1079 (#1065) 이모지 리액션 - 검색기능 추가
  public/index.html
  src/components/_common/post-footer/PostFooter.tsx
  src/components/comment-list/comment-input-box/CommentInputBox.tsx
  src/components/emoji-picker/EmojiPicker.helper.ts
  src/components/emoji-picker/EmojiPicker.tsx
  src/constants/layout.ts
  src/styles/global-styles.ts
Labels: feature
