Repository ssm0318/WhoamI-Today-frontend, pull requests merged in 2025-02, with the labels that each got.

#754 bugfix: #753 로그아웃시 세션스토리지에 저장된 스크롤 위치 정보 삭제
  src/constants/index.ts
  src/constants/sessionStorageKey.ts
  src/utils/apis/user.ts
Labels: bug

#765 (#732) ping api 연결
  public/icons/ping_emoji_add.svg
  public/icons/refresh.svg
  src/components/ping/ping-message-input/PingMessageInput.styled.ts
  src/components/ping/ping-message-input/PingMessageInput.tsx
  src/components/ping/ping-message-item/PingMessageItem.tsx
  src/components/profile/Profile.tsx
  src/components/user-page/UserPage.context.tsx
  src/constants/layout.ts
  src/design-system/SvgIcon/icons.ts
  src/hooks/useSWRInfiniteScroll.ts
  src/i18n/locales/en/translation.json
  src/i18n/locales/ko/translation.json
  src/index.tsx
  src/models/api/common.ts
  src/models/ping.ts
  src/routes/Root.tsx
  src/routes/UserPage.tsx
  src/routes/ping/Ping.tsx
  src/utils/apis/ping.ts
Labels: feature, ping

#769 (#764) 버전별 기능 플래그 상태 설정
  src/constants/featureFlag.ts
  src/models/api/user.ts
  src/routes/Root.tsx
  src/stores/user.ts
  src/utils/apis/user.ts
Labels: feature

#773 (#772) 게시글 작성시 placholder 추가 수정
  src/components/note/new-note-content/NewNoteContent.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/ko/translation.json
  src/routes/responses/NewResponse.tsx
Labels: common

#776 (#774) 친구페이지 - 친구 관계 표시 및 친구 관계 변경 모달 추가
  src/components/profile/Profile.tsx
  src/components/profile/edit-connections/EditConnectionsBottomSheet.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/ko/translation.json
  src/models/api/friends.ts
  src/models/user.ts
  src/utils/apis/friends.ts
Labels: feature, Friends
